---
- name: install git
  pacman: name=git
  become: yes

- name: configure git name
  git_config: name=user.name value="{{ archlinux_user_real_name }}" scope=global
  become: yes
  become_user: "{{ archlinux_username }}"

- name: configure git email
  git_config: name=user.email value="{{ archlinux_user_email }}" scope=global
  become: yes
  become_user: "{{ archlinux_username }}"

- name: configure global gitignore location
  git_config: name=core.excludesfile value="~/.gitignore" scope=global
  become: yes
  become_user: "{{ archlinux_username }}"

- name: configure global gitignore
  lineinfile: path=/home/{{ archlinux_username }}/.gitignore line={{ item }}
  with_items:
    - "*.swp"
    - "*.swo"
    - ".envrc"
    - ".direnv/"
    - ".vagrant.d/"
  become: yes
  become_user: "{{ archlinux_username }}"
