---
- name: remove vim minimal package
  pacman:
   name: vim
   state: absent
   force: true
  become: yes
  ignore_errors: yes

- name: install vim
  pacman:
    name: gvim
  become: yes

- name: create vim autoload directory
  file:
    path: "/home/{{ archlinux_username }}/.vim/autoload"
    owner: "{{ archlinux_username }}"
    group: users
    state: directory
  become: yes
  become_user: "{{ archlinux_username }}"

- name: install vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "/home/{{ archlinux_username }}/.vim/autoload/plug.vim"
  become: yes
  become_user: "{{ archlinux_username }}"

- name: configure .vimrc
  copy:
    src: vimrc
    dest: /home/{{ archlinux_username }}/.vimrc
    owner: {{ archlinux_username }}
    group: users
  become: yes
  become_user: "{{ archlinux_username }}"

- name: install and update Vim plugins
  command: "/usr/bin/vim +PlugUpdate +qall!"
  become: yes
  become_user: "{{ archlinux_username }}"

- name: update vim-plug
  command: "/usr/bin/vim +PlugUpgrade +qall!"
  become: yes
  become_user: "{{ archlinux_username }}"
